import { Product } from '@/types/product';

export const products: Product[] = [
{
  id: "herb-chamomile-1",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/1.png",
  name: "Chamomile",
  category: "herbs",
  rating: 4.5,
  botanicalName: "Matricaria chamomilla",
  availableForms: "Flowers - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "herb-calendula-petals-2",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/2.png",
  name: "Calendula Flowers",
  category: "herbs",
  rating: 5,
  botanicalName: "Calendula officinalis",
  availableForms: "Flowers - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "herb-calendula-petals-3",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/3.png",
  name: "Calendula Petals",
  category: "herbs",
  rating: 4.6,
  botanicalName: "Calendula officinalis",
  availableForms: "Petals - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "herb-moringa-4",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/4.png",
  name: "Moringa",
  category: "herbs",
  rating: 4.8,
  botanicalName: "Moringa oleifera",
  availableForms: "Leaves - Powder - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-marjoram-5",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/5.png",
  name: "Marjoram",
  category: "herbs",
  rating: 4.3,
  botanicalName: "Origanum majorana",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-parsley-6",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/6.png",
  name: "Parsley",
  category: "herbs",
  rating: 4.4,
  botanicalName: "Petroselinum crispum",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-basil-7",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/7.png",
  name: "Basil",
  category: "herbs",
  rating: 4.5,
  botanicalName: "Ocimum basilicum",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "herb-rosemary-8",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/8.png",
  name: "Rosemary",
  category: "herbs",
  rating: 4.6,
  botanicalName: "Salvia rosmarinus",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "herb-salmeka-9",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/9.png",
  name: "Salmeka",
  category: "herbs",
  rating: 4.7,
  botanicalName: "No Botanical Name",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-dill-10",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/10.png",
  name: "Dill",
  category: "herbs",
  rating: 4.8,
  botanicalName: "Anethum graveolens",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
  {
  id: "herb-crushed-mint-11",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/11.png",
  name: "Crushed Mint",
  category: "herbs",
  rating: 4.3,
  botanicalName: "Mentha spicata",
  availableForms: "Crushed Leaves - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-mint-leaves-12",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/12.png",
  name: "Mint Leaves",
  category: "herbs",
  rating: 4.4,
  botanicalName: "Mentha spicata",
  availableForms: "Whole Leaves - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
    isBestSeller: true,

},
{
  id: "herb-thyme-13",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/13.png",
  name: "Thyme",
  category: "herbs",
  rating: 4.5,
  botanicalName: "Thymus vulgaris",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-hibiscus-flowers-14",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/14.png",
  name: "Hibiscus Flowers",
  category: "herbs",
  rating: 4.6,
  botanicalName: "Hibiscus sabdariffa",
  availableForms: "Whole Flowers - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "herb-hibiscus-slices-15",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/15.png",
  name: "Hibiscus Slices",
  category: "herbs",
  rating: 5,
  botanicalName: "Hibiscus sabdariffa",
  availableForms: "Whole Flowers - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: false,
},
{
  id: "herb-hibiscus-tbc-16",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/16.png",
  name: "Hibiscus TBC",
  category: "herbs",
  rating: 4.7,
  botanicalName: "Hibiscus sabdariffa",
  availableForms: "TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
{
  id: "herb-dried-sage-17",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/17.png",
  name: "Dried Sage",
  category: "herbs",
  rating: 4.9,
  botanicalName: "Salvia officinalis",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
{
  id: "herb-guava-leaf-18",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/18.png",
  name: "Guava Leaf",
  category: "herbs",
  rating: 4.9,
  botanicalName: "Psidium guajava",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
{
  id: "herb-lemongrass-19",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/19.png",
  name: "Lemongrass",
  category: "herbs",
  rating: 4.6,
  botanicalName: "Cymbopogon citratus",
  availableForms: "Stems - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
    isBestSeller: true,

},
{
  id: "herb-laura-leaves-20",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/20.png",
  name: "Laura Leaves",
  category: "herbs",
  rating: 4.4,
  botanicalName: "Laurus nobilis",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
// Additional entries are handled the same way.

{
  id: "herb-henna-powder-21",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/21.png",
  name: "Henna Powder",
  category: "herbs",
  rating: 4.6,
  botanicalName: "Lawsonia inermis",
  availableForms: "Powder - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
{
  id: "herb-origano-22",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/22.png",
  name: "Origano",
  category: "herbs",
  rating: 4.8,
  botanicalName: "Origanum vulgare",
  availableForms: "Leaves - Dried - Powder",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
{
  id: "herb-molokhia-leaves-23",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/23.png",
  name: "Molokhia Leaves",
  category: "herbs",
  rating: 4.7,
  botanicalName: "Corchorus olitorius",
  availableForms: "Leaves - Dried - TBC",
  packing: "Paper Box",
  weight: "5 KG rr By Order",
  season: "All Year",
    isBestSeller: true,

},
{
  id: "herb-molokhia-crushed-24",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/24.png",
  name: "Molokhia-Crushed",
  category: "herbs",
  rating: 4.5,
  botanicalName: "Corchorus olitorius",
  availableForms: "Crushed Leaves - TBC",
  packing: "Polypropylene Package",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
},
{
  id: "herb-olive-leaves-25",
  url: "https://egyherbsglobal-770136110.imgix.net/Herbs/25.png",
  name: "Olive Leaves",
  category: "herbs",
  rating: 4.8,
  botanicalName: "Olea europaea",
  availableForms: "Leaves - Dried - TBC",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  },

  {
  id: "seed-cumin-1",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/1.png",
  name: "Cumin Seeds",
  category: "Seeds",
  rating: 4.2,
  reviews: 10,
  botanicalName: "Cuminum cyminum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-flaxseed-2",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/2.png",
  name: "Flaxseed",
  category: "Seeds",
  rating: 4.3,
  reviews: 13,
  botanicalName: "Linum usitatissimum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-fenugreek-3",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/3.png",
  name: "Fenugreek Seeds",
  category: "Seeds",
  rating: 4.4,
  reviews: 15,
  botanicalName: "Trigonella foenum-graecum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-coriander-4",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/4.png",
  name: "Coriander Seeds",
  category: "Seeds",
  rating: 4.5,
  reviews: 17,
  botanicalName: "Coriandrum sativum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-caraway-5",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/5.png",
  name: "Caraway Seeds",
  category: "Seeds",
  rating: 4.6,
  reviews: 20,
  botanicalName: "Carum carvi",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
    isBestSeller: true,

},
{
  id: "seed-nigella-6",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/6.png",
  name: "Cumin Black / Sativa Nigella",
  category: "Seeds",
  rating: 4.7,
  reviews: 25,
  botanicalName: "Nigella sativa",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-white-sesame-7",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/7.png",
  name: "White Sesame",
  category: "Seeds",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Sesamum indicum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "seed-peeled-sesame-8",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/8.png",
  name: "Peeled Sesame Seeds",
  category: "Seeds",
  rating: 4.3,
  reviews: 15,
  botanicalName: "Sesamum indicum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-golden-sesame-9",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/9.png",
  name: "Golden Sesame",
  category: "Seeds",
  rating: 4.4,
  reviews: 22,
  botanicalName: "Sesamum indicum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-anise-10",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/10.png",
  name: "Anise Seeds",
  category: "Seeds",
  rating: 4.5,
  reviews: 30,
  botanicalName: "Pimpinella anisum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-fennel-11",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/11.png",
  name: "Fennel Seeds",
  category: "Seeds",
  rating: 4.6,
  reviews: 17,
  botanicalName: "Foeniculum vulgare",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
    isBestSeller: true,

},
{
  id: "seed-sunflower-12",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/12.png",
  name: "Sunflower Seeds",
  category: "Seeds",
  rating: 4.7,
  reviews: 21,
  botanicalName: "Helianthus annuus",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "seed-basil-13",
  url: "https://egyherbsglobal-770136110.imgix.net/Seeds/13.png",
  name: "Basil Seeds",
  category: "Seeds",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Ocimum basilicum",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
  {
    id: "spice-horns-chili-1",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/1.png",
    name: "Horns Chili",
    category: "Spices",
    rating: 4.2,
    reviews: 10,
    botanicalName: "Capsicum annuum",
    availableForms: "Whole Pods - Dried",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-chili-powder-2",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/2.png",
    name: "Chili Powder",
    category: "Spices",
    rating: 4.3,
    reviews: 13,
    botanicalName: "Capsicum annuum",
    availableForms: "Powder",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-crushed-chili-3",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/3.png",
    name: "Crushed Chili",
    category: "Spices",
    rating: 4.4,
    reviews: 15,
    botanicalName: "Capsicum annuum",
    availableForms: "Crushed Flakes",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-paprika-sweet-4",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/4.png",
    name: "Paprika Sweet",
    category: "Spices",
    rating: 4.5,
    reviews: 17,
    botanicalName: "Capsicum annuum",
    availableForms: "Powder",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-turmeric-powder-5",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/5.png",
    name: "Turmeric Powder",
    category: "Spices",
    rating: 4.6,
    reviews: 20,
    botanicalName: "Curcuma longa",
    availableForms: "Powder",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-turmeric-fingers-6",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/6.png",
    name: "Turmeric Fingers",
    category: "Spices",
    rating: 4.7,
    reviews: 25,
    botanicalName: "Curcuma longa",
    availableForms: "Whole Rhizomes - Dried",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-cinnamon-7",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/7.png",
    name: "Cinnamon",
    category: "Spices",
    rating: 4.8,
    reviews: 28,
    botanicalName: "Cinnamomum verum",
    availableForms: "Sticks / Powder",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-arabic-gum-8",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/8.png",
    name: "Arabic Gum",
    category: "Spices",
    rating: 4.3,
    reviews: 15,
    botanicalName: "Acacia senegal",
    availableForms: "Gum - Dried",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
    id: "spice-cloves-9",
    url: "https://egyherbsglobal-770136110.imgix.net/Spices/9.png",
    name: "Cloves",
    category: "Spices",
    rating: 4.4,
    reviews: 22,
    botanicalName: "Syzygium aromaticum",
    availableForms: "Whole Buds - Dried",
    packing: "Polypropylene Package - Paper Box",
    weight: "10 KG – 20 KG – 24 KG",
    season: "All Year",
  },
  {
  id: "spice-frankincense-10",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/10.png",
  name: "Frankincense",
  category: "Spices",
  rating: 4.5,
  reviews: 30,
  botanicalName: "Boswellia sacra",
  availableForms: "Resin - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-yellow-lemon-11",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/11.png",
  name: "Yellow Lemon",
  category: "Spices",
  rating: 4.6,
  reviews: 17,
  botanicalName: "Citrus limon",
  availableForms: "Whole Lemons - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "spice-black-lemon-12",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/12.png",
  name: "Black Lemon",
  category: "Spices",
  rating: 4.7,
  reviews: 21,
  botanicalName: "Citrus limon",
  availableForms: "Whole Lemons - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
  isBestSeller: true,
},
{
  id: "spice-ginger-13",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/13.png",
  name: "Ginger",
  category: "Spices",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Zingiber officinale",
  availableForms: "Whole Rhizomes / Powder - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-black-pepper-14",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/14.png",
  name: "Black Pepper",
  category: "Spices",
  rating: 4.3,
  reviews: 15,
  botanicalName: "Piper nigrum",
  availableForms: "Whole Peppercorns / Ground - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-onion-powder-15",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/15.png",
  name: "Onion Powder",
  category: "Spices",
  rating: 4.4,
  reviews: 22,
  botanicalName: "Allium cepa",
  availableForms: "Powder",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-onion-slices-16",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/16.png",
  name: "Onion Slices",
  category: "Spices",
  rating: 4.5,
  reviews: 30,
  botanicalName: "Allium cepa",
  availableForms: "Dried Slices",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-dried-garlic-17",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/17.png",
  name: "Dried Garlic",
  category: "Spices",
  rating: 4.6,
  reviews: 17,
  botanicalName: "Allium sativum",
  availableForms: "Dried Flakes / Powder",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year",
    isBestSeller: true,

},
{
  id: "spice-carob-18",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/18.png",
  name: "Carob",
  category: "Spices",
  rating: 4.7,
  reviews: 21,
  botanicalName: "Ceratonia siliqua",
  availableForms: "Whole Pods - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-liquorice-19",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/19.png",
  name: "Liquorice",
  category: "Spices",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Glycyrrhiza glabra",
  availableForms: "Root - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-orange-peel-20",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/20.png",
  name: "Dried Orange Peel",
  category: "Spices",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Citrus sinensis",
  availableForms: "Dried Peel",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "spice-cardamom-21",
  url: "https://egyherbsglobal-770136110.imgix.net/Spices/21.png",
  name: "Cardamom",
  category: "Spices",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Elettaria cardamomum",
  availableForms: "Whole Pods - Dried",
  packing: "Polypropylene Package - Paper Box",
  weight: "10 KG – 20 KG – 24 KG",
  season: "All Year"
},
{
  id: "legume-chickpea-beans-1",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/1.png",
  name: "Chickpea Beans",
  category: "Legumes",
  rating: 4.2,
  reviews: 10,
  botanicalName: "Cicer arietinum",
  availableForms: "Beans",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-white-beans-2",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/2.png",
  name: "White Beans",
  category: "Legumes",
  rating: 4.3,
  reviews: 13,
  botanicalName: "Phaseolus vulgaris",
  availableForms: "Beans",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
    isBestSeller: true,

},
{
  id: "legume-green-lentils-3",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/3.png",
  name: "Green Lentils",
  category: "Legumes",
  rating: 4.4,
  reviews: 15,
  botanicalName: "Lens culinaris",
  availableForms: "Lentils",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-lentils-4",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/4.png",
  name: "Lentils",
  category: "Legumes",
  rating: 4.5,
  reviews: 17,
  botanicalName: "Lens culinaris",
  availableForms: "Lentils",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-vigna-seeds-5",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/5.png",
  name: "Vigna Seeds",
  category: "Legumes",
  rating: 4.6,
  reviews: 20,
  botanicalName: "Vigna spp.",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-grits-6",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/6.png",
  name: "Grits",
  category: "Legumes",
  rating: 4.7,
  reviews: 25,
  botanicalName: "Zea mays",
  availableForms: "Coarse Ground Corn",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-popcorn-seeds-7",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/7.png",
  name: "Popcorn Seeds",
  category: "Legumes",
  rating: 4.8,
  reviews: 28,
  botanicalName: "Zea mays everta",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-lupine-8",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/8.png",
  name: "Lupine",
  category: "Legumes",
  rating: 4.3,
  reviews: 15,
  botanicalName: "Lupinus spp.",
  availableForms: "Seeds",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
},
{
  id: "legume-broad-bean-9",
  url: "https://egyherbsglobal-770136110.imgix.net/Legumes/9.png",
  name: "Broad Bean",
  category: "Legumes",
  rating: 4.4,
  reviews: 22,
  botanicalName: "Vicia faba",
  availableForms: "Beans",
  packing: "Polypropylene Package",
  weight: "25 KG – 50 KG",
  season: "All Year",
    isBestSeller: true,

},
];